apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mbd4yquuf-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:7394ff92e65820231164d8454363a2cddef1fb74@sha256:ddd4aba6f10747afa95c252ff068fec47cfcce142b4aaac4bb133c8cff3e9a26
          name: container-image
