apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mbd4yquuf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mbd4yquuf-go 
  name: mbd4yquuf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mbd4yquuf-go 
